events{}

http {
    upstream frontend_dev_server {
        server frontend-dev:5173;
    }

    upstream go_server {
            server go-server:5155;
    }

    upstream imputer_service {
            server imputer-service:8008;
    }

    server {
        listen 80;
        client_max_body_size 1G;

        location / {
            proxy_set_header Host $host;
            proxy_pass http://frontend_dev_server;
        }

        location /api/ {
            proxy_set_header Host $host;
            proxy_pass http://go_server/;
        }
        
        location /imputer/ {
            proxy_set_header Host $host;
            proxy_pass http://imputer_service/;
        }

    }

}
