server {
    listen 80;
    listen [::]:80;

    location / {
        proxy_pass http://127.0.0.1:5173; 
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:5155/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /imputer/ {
        proxy_pass http://127.0.0.1:8008/;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
