events{}

http {
    upstream frontend_dev_server {
        server frontend-dev:5173;
    }

    upstream go_server {
            server go-server:5155;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_dev_server;
        }

        location /api/ {
            proxy_pass http://go_server/;
        }

    }

}
