version: "2"

issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports
    - golines
    - gofmt
    - swaggo

  settings:
    golines:
      # Default: 100
      max-len: 120

linters:
  enable:
    - errcheck
    - godoclint
    - govet
    - ineffassign
    - unparam
    - unused

